version: '3'
services:
  spark:
    build:
      dockerfile: docker/spark/Dockerfile
    container_name: spark-container
    ports:
      - "4040:4040" # Spark Web UI
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTH_SECRET=mysecret
    volumes:
      - app:/app  # Mount your Spark application directory here

  mysql:
    image: mariadb:latest
    container_name: mariadb-container
    ports:
      - "3306:3306"  # MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: verystrongrootpassword123*
      MYSQL_DATABASE: star_classification
      MYSQL_USER: nasa
      MYSQL_PASSWORD: verystrongpassword123*
    volumes:
      - ./docker/mariadb/data:/var/lib/mariadb  # Mount a data directory for mariadb
